{% set name = "napari-convpaint" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: be0fdde4882aada22e83177a375d700c8ab6fd0968346c601b531d921e5ed399

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - wheel
  run:
    - catboost >=1.2.8
    - einops
    - joblib
    - magicgui
    - napari
    - napari-annotation-project
    - napari-guitils
    - numpy
    - omegaconf
    - pandas
    - python >={{ python_min }}
    - pytorch
    - pyyaml
    - qtpy
    - scikit-image
    - scikit-learn
    - tifffile
    - timm
    - torchvision >=0.13.0
    - zarr

test:
  imports:
    - napari_convpaint
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-convpaint
  summary: A plugin for segmentation by pixel classification using convolutional feature extraction
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/guiwitz/napari-convpaint

extra:
  recipe-maintainers:
    - guiwitz
    - goanpeca
    - jaimergp
