{% set name = "napari-convpaint" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-convpaint-{{ version }}.tar.gz
  sha256: 07ae63c8dfb616a8e30b968d635791d6d8c618d9100eec9cd6a9bc3ade67024f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
    - setuptools-scm
    - wheel
  run:
    - einops
    - joblib
    - magicgui
    - napari
    - napari-guitils
    - napari-annotation-project
    - numpy
    - pandas
    - python >=3.8
    - pytorch
    - pyyaml
    - qtpy
    - scikit-image
    - scikit-learn
    - tifffile
    - torchvision
    - zarr

test:
  imports:
    - napari_convpaint
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/napari-convpaint
  summary: A plugin for segmentation by pixel classification using convolutional feature extraction
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/guiwitz/napari-convpaint

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
