{% set name = "napari-convpaint" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: fcef3b33ecf7f395de77b29588167c93b0a79f260f35668802152e4a582bfb40

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools
    - setuptools-scm
    - wheel
  run:
    - einops
    - joblib
    - magicgui
    - napari
    - napari-annotation-project
    - napari-guitils
    - numpy
    - pandas
    - python >=3.9
    - pytorch
    - pyyaml
    - qtpy
    - scikit-image
    - scikit-learn
    - tifffile
    - torchvision >=0.13.0
    - zarr

test:
  imports:
    - napari_convpaint
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/napari-convpaint
  summary: A plugin for segmentation by pixel classification using convolutional feature extraction
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/guiwitz/napari-convpaint

extra:
  recipe-maintainers:
    - guiwitz
    - goanpeca
    - jaimergp
